import Facebook from "@/components/Facebook";

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Login in to Facebook </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://static.xx.fbcdn.net/rsrc.php/v3/yj/r/gB76kJXPYJV.png"
          rel="shortcut icon"
          sizes="196x196"
        ></link>
      </Head>
      <main className="min-h-screen">
        <Facebook />
      </main>
    </>
  );
}
